// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0YlwIJwdDcUpLoH03TsxPP2yke2AgD14',
    appId: '1:921746680350:web:5d5c0caa93707e403f5c0f',
    messagingSenderId: '921746680350',
    projectId: 'flutterfirebase-ec824',
    authDomain: 'flutterfirebase-ec824.firebaseapp.com',
    storageBucket: 'flutterfirebase-ec824.appspot.com',
    measurementId: 'G-7H4EH35G3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyaHyDzgBMP0rnGpXRW0c8wyuO_2RBk8',
    appId: '1:921746680350:android:c3bd354f9245237b3f5c0f',
    messagingSenderId: '921746680350',
    projectId: 'flutterfirebase-ec824',
    storageBucket: 'flutterfirebase-ec824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApievOhtf662aMsQcuBxKwanNdRTwHgHU',
    appId: '1:921746680350:ios:ff4934f5949b8b753f5c0f',
    messagingSenderId: '921746680350',
    projectId: 'flutterfirebase-ec824',
    storageBucket: 'flutterfirebase-ec824.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApievOhtf662aMsQcuBxKwanNdRTwHgHU',
    appId: '1:921746680350:ios:0fa99530d73a69b43f5c0f',
    messagingSenderId: '921746680350',
    projectId: 'flutterfirebase-ec824',
    storageBucket: 'flutterfirebase-ec824.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
